# Generated by Django 5.2.8 on 2025-11-13 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subject',
            table='Subject',
        ),
        migrations.AlterModelTable(
            name='trainer',
            table='Trainer',
        ),
    ]
