# Generated by Django 5.2.3 on 2025-11-14 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_app', '0002_alter_subject_table_alter_trainer_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name': 'Trainer', 'verbose_name_plural': 'Trainers'},
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='emp_id',
            new_name='trainer_code',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='subject',
        ),
        migrations.AlterModelTable(
            name='trainer',
            table='trainer',
        ),
    ]
